name: Security & Quality Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-tests:
    name: Security & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq shellcheck
        
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
        
    - name: Verify project structure
      run: |
        echo "📋 Project Structure Verification"
        echo "================================="
        
        # Check for required directories
        test -d scripts/lib || { echo "❌ Missing scripts/lib directory"; exit 1; }
        test -d tests || { echo "❌ Missing tests directory"; exit 1; }
        
        # Check for critical security files
        test -f scripts/lib/security-utils.sh || { echo "❌ Missing security-utils.sh"; exit 1; }
        test -f scripts/lib/error-utils.sh || { echo "❌ Missing error-utils.sh"; exit 1; }
        test -f .shellcheckrc || { echo "❌ Missing .shellcheckrc"; exit 1; }
        test -f .gitignore || { echo "❌ Missing .gitignore"; exit 1; }
        
        echo "✅ All required files present"
        
    - name: Run ShellCheck linting
      run: |
        echo "🔍 Running ShellCheck on all scripts"
        echo "====================================="
        
        # Find and check all shell scripts
        EXIT_CODE=0
        
        find . -name "*.sh" -type f | while read -r script; do
          echo "Checking: $script"
          if ! shellcheck "$script"; then
            EXIT_CODE=1
          fi
        done
        
        exit $EXIT_CODE
        
    - name: Test security utilities
      run: |
        echo "🧪 Testing Security Functions"
        echo "============================="
        
        # Source security utilities and test basic functions
        cd scripts
        source lib/security-utils.sh
        
        # Test input validation
        echo "Testing validate_issue_number..."
        
        # Valid inputs should pass
        validate_issue_number "42" || { echo "❌ Failed valid input test"; exit 1; }
        validate_issue_number "123" || { echo "❌ Failed valid input test"; exit 1; }
        
        # Invalid inputs should fail
        ! validate_issue_number "abc" || { echo "❌ Failed invalid input test"; exit 1; }
        ! validate_issue_number "'; DROP TABLE users;--" || { echo "❌ Failed injection test"; exit 1; }
        ! validate_issue_number "" || { echo "❌ Failed empty input test"; exit 1; }
        
        echo "✅ Security validation tests passed"
        
    - name: Test script security hardening
      run: |
        echo "🛡️ Testing Security Hardening"
        echo "============================="
        
        # Mock GitHub CLI for testing
        mkdir -p ~/.local/bin
        cat > ~/.local/bin/gh << 'EOF'
        #!/bin/bash
        if [[ "$1" == "auth" && "$2" == "status" ]]; then
          echo "✓ Logged in to github.com as test-user"
          exit 0
        fi
        echo "Mock gh command: $*"
        exit 0
        EOF
        chmod +x ~/.local/bin/gh
        export PATH="$HOME/.local/bin:$PATH"
        
        # Create minimal test config
        cat > config.json << 'EOF'
        {
          "github": {
            "owner": "test-owner",
            "repository": "test-repo"
          },
          "project": {
            "id": "PVT_test123",
            "url": "https://github.com/users/test-owner/projects/1",
            "number": 1
          }
        }
        EOF
        
        # Test key scripts reject malicious input
        echo "Testing injection attack prevention..."
        
        # Test SQL injection
        if ./scripts/workflow/start-workflow-task.sh --dry-run "'; DROP TABLE users;--" 2>&1 | grep -q "must be numeric"; then
          echo "✅ SQL injection properly rejected"
        else
          echo "❌ SQL injection vulnerability detected"
          exit 1
        fi
        
        # Test GraphQL injection  
        if ./scripts/workflow/review-workflow-task.sh --dry-run '"; } mutation { deleteAll } { "' 2>&1 | grep -q "must be numeric"; then
          echo "✅ GraphQL injection properly rejected"
        else
          echo "❌ GraphQL injection vulnerability detected"
          exit 1
        fi
        
        # Test command injection
        if ./scripts/workflow/complete-task.sh --dry-run '$(rm -rf /)' 2>&1 | grep -q "must be numeric"; then
          echo "✅ Command injection properly rejected"
        else
          echo "❌ Command injection vulnerability detected"
          exit 1
        fi
        
        echo "🎉 All security tests passed!"
        
    - name: Verify no sensitive data in repo
      run: |
        echo "🔒 Checking for sensitive data"
        echo "============================="
        
        # Check for potential secrets or API keys
        if git log --all --full-history -- config.json | grep -q "config.json"; then
          echo "⚠️  config.json found in git history - verify no secrets committed"
        fi
        
        # Check for hardcoded secrets patterns (more specific to avoid false positives)
        if grep -rE "ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{82}|sk-[a-zA-Z0-9]{48}" . --exclude-dir=.git; then
          echo "❌ Potential secrets found in repository"
          exit 1
        fi
        
        echo "✅ No sensitive data detected"
        
    - name: Test dry-run mode safety
      run: |
        echo "🧪 Testing Dry-Run Safety"
        echo "========================="
        
        # Create mock configuration for testing
        cp config-template.json config.json
        sed -i 's/YOUR_GITHUB_USERNAME/test-user/g' config.json
        sed -i 's/YOUR_REPOSITORY_NAME/test-repo/g' config.json
        sed -i 's/YOUR_PROJECT_ID/PVT_test123/g' config.json
        sed -i 's/TASK_TYPE_FIELD_ID/PVTSSF_task_type/g' config.json
        sed -i 's/RISK_LEVEL_FIELD_ID/PVTSSF_risk_level/g' config.json
        sed -i 's/EFFORT_FIELD_ID/PVTSSF_effort/g' config.json
        sed -i 's/STATUS_FIELD_ID/PVTSSF_status/g' config.json
        sed -i 's/DEPENDENCIES_FIELD_ID/PVTSSF_dependencies/g' config.json
        
        echo "✅ Mock configuration created"
        
        # Mock GitHub CLI for testing
        export PATH="$HOME/.local/bin:$PATH"
        
        # Verify dry-run mode doesn't make actual changes
        echo "Testing dry-run mode prevents actual execution..."
        
        # All these should complete without errors and without making real changes
        ./scripts/workflow/start-workflow-task.sh --dry-run 42 || { echo "❌ start-workflow-task dry-run failed"; exit 1; }
        ./scripts/workflow/review-workflow-task.sh --dry-run 42 "test" || { echo "❌ review-workflow-task dry-run failed"; exit 1; }
        ./scripts/workflow/complete-task.sh --dry-run 42 "test" || { echo "❌ complete-task dry-run failed"; exit 1; }
        
        echo "✅ Dry-run mode working correctly"

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check file headers
      run: |
        echo "📝 Checking File Headers"
        echo "========================"
        
        missing_headers=0
        
        # Check that main scripts have proper headers
        for script in scripts/*/*.sh; do
          if [[ -f "$script" ]] && ! grep -q "@fileoverview" "$script"; then
            echo "❌ Missing header: $script"
            missing_headers=$((missing_headers + 1))
          fi
        done
        
        if [[ $missing_headers -gt 0 ]]; then
          echo "❌ $missing_headers scripts missing proper headers"
          exit 1
        fi
        
        echo "✅ All scripts have proper headers"
        
    - name: Check documentation completeness
      run: |
        echo "📚 Documentation Completeness"
        echo "============================="
        
        # Check for key documentation files
        test -f README.md || { echo "❌ Missing README.md"; exit 1; }
        test -f SECURITY_IMPROVEMENTS_COMPLETE.md || { echo "❌ Missing security documentation"; exit 1; }
        
        # Check README has basic sections
        grep -q "Installation" README.md || { echo "❌ README missing Installation section"; exit 1; }
        grep -q "Usage" README.md || { echo "❌ README missing Usage section"; exit 1; }
        
        echo "✅ Documentation complete"

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [security-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        
    - name: Test configuration system
      run: |
        echo "⚙️ Testing Configuration System"
        echo "==============================="
        
        # Test config template exists
        test -f config-template.json || { echo "❌ Missing config-template.json"; exit 1; }
        
        # Validate JSON syntax
        jq . config-template.json > /dev/null || { echo "❌ Invalid JSON in config-template.json"; exit 1; }
        
        # Test config loading
        source scripts/lib/config-utils.sh
        
        # Create test config
        cp config-template.json config.json
        sed -i 's/YOUR_GITHUB_USERNAME/test-user/g' config.json
        sed -i 's/YOUR_REPOSITORY_NAME/test-repo/g' config.json
        sed -i 's/YOUR_PROJECT_ID/PVT_test123/g' config.json
        
        # Test config validation
        if validate_config; then
          echo "✅ Configuration system working"
        else
          echo "❌ Configuration system failed"
          exit 1
        fi

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [security-tests, code-quality, integration-tests]
    if: always()
    
    steps:
    - name: Report results
      run: |
        echo "🎯 Test Summary"
        echo "==============="
        echo "Security Tests: ${{ needs.security-tests.result }}"
        echo "Code Quality: ${{ needs.code-quality.result }}"
        echo "Integration: ${{ needs.integration-tests.result }}"
        
        if [[ "${{ needs.security-tests.result }}" == "success" && \
              "${{ needs.code-quality.result }}" == "success" && \
              "${{ needs.integration-tests.result }}" == "success" ]]; then
          echo ""
          echo "🎉 ALL TESTS PASSED!"
          echo "✅ Security: HARDENED"
          echo "✅ Quality: VERIFIED" 
          echo "✅ Integration: WORKING"
          echo ""
          echo "🚀 Ready for production use!"
        else
          echo ""
          echo "❌ Some tests failed - review and fix issues"
          exit 1
        fi